const cardData = [
  {
    id: 1,
    image: '/images/projects/GeneralStoreFrontend.webp',
    tags: ['NextJS', 'MongoDB', 'Jest/RTL', 'Cypress'],
    title: 'General Store Frontend',
    description: 'eCommerce App Frontend',
    live: 'https://store-frontend-aegisnull.vercel.app',
    github: 'https://github.com/aegisnull/general-store-frontend',
  },
  {
    id: 2,
    image: '/images/projects/GeneralStoreBackend.webp',
    tags: ['ExpressJS', 'MongoDB', 'K6'],
    title: 'General Store Backend',
    description: 'eCommerce App Backend',
    live: 'http://news-explorer.projects.luistellez.com',
    github: 'https://github.com/aegisnull/general-store-backend',
  },
  {
    id: 3,
    image: '/images/projects/ReactCalendar.webp',
    tags: ['VitéJS', 'JS Date'],
    title: 'React Calendar',
    description: 'React Calendar App',
    live: 'https://react-calendar-altomobile.netlify.app',
    github: 'https://github.com/aegisnull/react-calendar',
  },
  {
    id: 4,
    image: '/images/projects/NewsExplorer.webp',
    tags: ['React', 'NodeJS', 'ExpressJS', 'MongoDB'],
    title: 'News Explorer',
    description: 'News Reader Full Stack App',
    live: 'http://news-explorer.projects.luistellez.com',
    github: 'https://github.com/aegisnull/news-explorer-frontend',
  },
  {
    id: 5,
    image: '/images/projects/Moody.webp',
    tags: ['HTML', 'CSS', 'JavaScript'],
    title: 'Moody',
    description: 'Hackathon Project Landing Page',
    live: 'https://moody-app.netlify.app',
    github: 'https://github.com/aegisnull/moody',
  },
  {
    id: 6,
    image: '/images/projects/AroundTheUS.webp',
    tags: ['React', 'NodeJS', 'ExpressJS', 'MongoDB'],
    title: 'Around The U.S.',
    description: 'Instagram like app',
    live: 'http://aroundus.projects.luistellez.com',
    github: 'https://github.com/aegisnull/react-around-api-full_es',
  },
  {
    id: 7,
    image: '/images/projects/GMG.webp',
    tags: ['WordPress', 'PHP', 'HTML', 'CSS'],
    title: 'GMG Manufacturing',
    description: 'Local Manufacturing  Website',
    live: 'https://web.archive.org/web/20221208215442/https://gmgmanufacturing.com/',
  },
  {
    id: 8,
    image: '/images/projects/CirculoCafe.webp',
    tags: ['HTML', 'CSS', 'jQuery'],
    title: 'Circulo Café',
    description: 'Coffee Shop Website',
    live: 'https://circulocafe.com',
  },
  {
    id: 9,
    image: '/images/projects/PreparaTuConta.webp',
    tags: ['HTML', 'CSS', 'jQuery'],
    title: 'Prepara tu Conta',
    description: 'Accounting Website',
    live: 'https://aegisnull.github.io/prepara-tu-conta/',
  },
  {
    id: 10,
    image: '/images/projects/PatriaAPatria.webp',
    tags: ['HTML', 'CSS', 'CSS Grid'],
    title: 'Practicum Art Gallery',
    description: 'Art Gallery Website',
    live: 'https://aegisnull.github.io/practicum-art-gallery/',
    github: 'https://github.com/aegisnull/practicum-art-gallery',
  },
  {
    id: 11,
    image: '/images/projects/AprenderAAprender.webp',
    tags: ['HTML', 'CSS', 'BEM'],
    title: 'Aprender a Aprender',
    description: 'Learning Info Website',
    live: 'https://aegisnull.github.io/aprender-a-aprender/',
    github: 'https://github.com/aegisnull/aprender-a-aprender',
  },
  {
    id: 12,
    image: '/images/projects/Memorama.webp',
    tags: ['HTML', 'CSS', 'JavaScript'],
    title: 'Memorama Game',
    description: 'Memory Game Website',
    live: 'https://aegisnull.github.io/memorama/',
    github: 'https://github.com/aegisnull/memorama',
  },
  {
    id: 13,
    image: '/images/projects/Intelegal.webp',
    tags: ['WordPress', 'PHP', 'HTML', 'CSS'],
    title: 'Intelegal',
    description: 'Website for Law Firm',
    live: 'https://intelegal.com.mx',
  },
  {
    id: 14,
    image: '/images/projects/OdinLandingPage.webp',
    tags: ['HTML', 'CSS'],
    title: 'Odin Landing Page',
    description: 'Simple Landing Page',
    live: 'https://aegisnull.github.io/odin-landing-page/',
    github: 'https://github.com/aegisnull/odin-landing-page',
  },
  {
    id: 15,
    image: '/images/projects/IntelegalLandingPage.webp',
    tags: ['WordPress', 'PHP', 'HTML', 'CSS'],
    title: 'Intelegal Landing Page',
    description: 'Landing Page for Real Estate',
    live: '#',
  },
];

export default cardData;

// images should be 330x201 pixels
